name: Deploy

on:
    push:
        paths-ignore:
            - "resources/*"
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build
              uses: actions/setup-node@v1
            - run: npm install
            - run: npm run build

            - name: copy files via scp
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  source: "build/."
                  rm: true
                  target: /var/www/project/corona
                  strip_components: 1
